### ISSUE TITLE
Separate messages with significant time difference.

### ISSUE THREAD

**Issue by Aareon** [AnonymousDapper/rwci-client#6]
A simple horizontal rule would suffice. Just something that keeps the eye from wandering.

**Comment by AnonymousDapper** [comment]
I don't know that an hrule separator really fits with the aesthetic I want for this. Maybe an extra linebreak or something similar would be a better look.

**Comment by Aareon** [comment]
[time] Author: Message
    ...
    [time] Author: Message

This is also a valid option to separate messages with significantly different times.

**Comment by AnonymousDapper** [comment]
This is also taken care of in 64f431c
