### ISSUE TITLE
Change LICENSE to GPL

### ISSUE THREAD

**Issue by Aareon** [AnonymousDapper/rwci-client#7]
Issue being, a non-commercially licensed application using the PyQt software must be licensed with the GNU Public License to avoid Copyright infringement and/or a DMCA takedown.

**Comment by BurntRouter** [comment]
![flat 800x800 075 t](https://user-images.githubusercontent.com/10344271/31801437-259a70a2-b516-11e7-9d17-0379081f76ba.jpg)

**Comment by Aareon** [comment]
https://www1.qt.io/faq/#_Toc_3_4

**Comment by AnonymousDapper** [comment]
Is there a way to select a new license for the repo or do I have to put the license text in `LICENSE` and it'll detect the license? @Aareon

**Comment by AnonymousDapper** [comment]
This is taken care of in  64f431c
